export const SHOW_ALERT = "SHOW_ALERT";
export const ALERT_CONFIRM = "ALERT_CONFIRM";
export const ALERT_PROCESS = "ALERT_PROCESS";
export const ALERT_APPROVE = "ALERT_APPROVE";
export const ALERT_DECLINE = "ALERT_DECLINE";
export const ALERT_COMPLETED = "ALERT_COMPLETED";
