export const GET_All = "GET_ALL";
export const ADD_CONDITION = "ADD_CONDITION";
export const DELETE_CONDITION = "DELETE_CONDITION";
export const DETAIL_CONDITION = "DETAIL_CONDITION";
export const UPDATE_CONDITION = "UPDATE_CONDITION";
