export const GET_ALL_LOCATION = "GET_ALL_LOCATION";
export const ALL_LOCATION_WITH_PAGINAITON = "ALL_LOCATION_WITH_PAGINAITON";
export const ADD_LOCATION = "ADD_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const DETAIL_LOCATION = "DETAIL_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
