export const GET_ALL_POSITION = "GET_ALL_POSITION";
export const ALL_POSITION_WITH_PAGINATION = "ALL_POSITION_WITH_PAGINATION";
export const ADD_POSITION = "ADD_POSITION";
export const DETAIL_POSITION = "DETAIL_POSITION";
export const DELETE_POSITION = "DELETE_POSITION";
export const UPDATE_POSITION = "UPDATE_POSITION";
