export const GET_ALL_WORK_UNIT = "GET_ALL_WORK_UNIT";
export const ALL_WORK_UNIT_WITH_PAGINATION = "ALL_WORK_UNIT_WITH_PAGINATION";
export const CREATE_WORK_UNIT = "CREATE_WORK_UNIT";
export const DETAIL_WORK_UNIT = "DETAIL_WORK_UNIT";
export const DELETE_WORK_UNIT = "DELETE_WORK_UNIT";
export const UPDATE_WORK_UNIT = "UPDATE_WORK_UNIT";
